Fix(nginx-config): Listen port based on nextcloud.containerPort
nextcloud/helm pull request #278
Opened 2022-09-06 16:31 UTC by Nold360

Signed-off-by: nold <nold@gnu.one>

# Pull Request

## Description of the change

If `nextcloud.containerPort` is set, it will configure nginx to listen to the specified port.

## Benefits

Allows nginx container to run rootless & follows the expected behavior of `nextcloud.containerPort`.

## Possible drawbacks

Unexpected port change on update?!

## Applicable issues

- fixes #

## Additional information

## Checklist 

- [x] DCO has been [signed off on the commit](https://docs.github.com/en/github/authenticating-to-github/signing-commits).
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] (optional) Variables are documented in the README.md

2022-09-06 17:00 UTC, tvories commented
Thanks for the submission @Nold360 .  can you bump the chart version?

2022-09-06 18:20 UTC, Nold360 commented
> Thanks for the submission @Nold360 . can you bump the chart version?

fixed

2022-11-27 05:05 UTC, relrod commented
+1, this seems necessary for OpenShift.

For now I've worked around this using the normal apache image, as an image stream and layered a change on top of it to make it listen on another port, but this is a much cleaner solution.

I also think the readiness probes also need to be able to have their ports configured, because that was the next issue I ran into on OpenShift. They seem to hardcode `port: http` right now.

2023-01-25 06:32 UTC, provokateurin requested changes

2023-01-25 06:32 UTC, provokateurin commented on charts/nextcloud/templates/nginx-config.yaml
> +            listen {{ .Values.nextcloud.containerPort | default 80 }};
Could you move the default value into the values file? That would make it easier to reuse for https://github.com/nextcloud/helm/pull/316

2023-04-25 05:56 UTC, provokateurin commented on charts/nextcloud/templates/nginx-config.yaml
> +            listen {{ .Values.nextcloud.containerPort | default 80 }};
Yes

2023-04-29 08:48 UTC, closed without merging