Fix namespace selector
nextcloud/helm pull request #349
Opened 2023-02-14 18:06 UTC by Richardds

# Pull Request

## Description of the change

The current configuration does not work when the monitored service runs outside of the `serviceMonitor`'s namespace.

Other helm charts, such as [bitnami/redis](https://github.com/bitnami/charts/tree/main/bitnami/redis) use `namespaceSelector` to fix this [[1](https://github.com/bitnami/charts/blob/71af6a6b0c6070a4bd9d2e4466c9daf3c8c612ab/bitnami/redis/templates/servicemonitor.yaml#L38)].

## Benefits

The `serviceMonitor` is now able to find the monitored service.

## Possible drawbacks

## Applicable issues

## Additional information

Example of `metrics` section from `values.yaml`:
```yaml
...
metrics:
  enabled: true
  token: <token>
  serviceMonitor:
    enabled: true
    namespace: monitoring
    labels:
      release: prometheus
```

## Checklist 

- [ ] DCO has been [signed off on the commit](https://docs.github.com/en/github/authenticating-to-github/signing-commits).
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] (optional) Variables are documented in the README.md

2023-02-19 17:16 UTC, Richardds commented
Hello @jessebot , I bumped the version to `3.5.1`.

2023-03-19 12:26 UTC, Richardds commented on charts/nextcloud/templates/metrics-servicemonitor.yaml
> +      - {{ .Release.Namespace }}
Hi @jessebot , I adjusted the code as suggested.

2023-11-21 12:32 UTC, wrenix requested changes
I miss a documentation in the `values.yaml`

2023-11-21 12:32 UTC, wrenix commented on charts/nextcloud/templates/metrics-servicemonitor.yaml
> +    {{- if .Values.metrics.serviceMonitor.namespace }}
```suggestion:+2
    {{- with .Values.metrics.serviceMonitor.namespace }}
    - {{ . | quote }}
```

2023-11-21 12:34 UTC, wrenix commented on charts/nextcloud/templates/metrics-servicemonitor.yaml
> +    {{- if .Values.metrics.serviceMonitor.namespace }}
1. with is easy reable
2. so multiple namespaces are configurable

2024-02-05 07:36 UTC, wrenix commented
i believe we could close this PR now ;)
#524 was merged

2024-02-05 09:12 UTC, provokateurin commented
You're right

2024-02-05 09:12 UTC, closed without merging