Do not define loadBalancerIP on service unless set in values
nextcloud/helm pull request #430
Opened 2023-08-18 01:52 UTC by benyanke

# Pull Request

## Description of the change

This PR sets the `.Values.service.loadBalancerIP` field as optional, and does not define it in the service if it's not set in the values.

This is because some `LoadBalancer` implementations allow or even require this value to remain unset, and while it may sometimes be fine to leave it set but blank, this could have unexpected impacts depending on your cluster configuration.

In particular, `MetalLB` will leave the service `<pending>` if the `loadBalancerIP` is set to `nil`, and hardcoding it to a value in the values breaks the ability for `MetalLB`'s IPAM tooling to be used for dynamic address allocation. I suspect other LoadBalancer implementations may have similar behaviors.

## Benefits

 The primary benefit is more flexible usage with more `LoadBalancer` implementations.

## Possible drawbacks

None I can think of, however I am open to discussion.

## Applicable issues

 - fixes #428

## Additional information

For easy review on the output, here is the before and after:

## After - No LB set

Note how the `loadBalancerIP` is now gone when it's not defined, for more flexible usage.

```bash
$ helm template nextcloud . --set service.type=LoadBalancer | grep Service -A 15
kind: Service
metadata:
  name: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    helm.sh/chart: nextcloud-3.6.0
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: app
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
```

## After - LB Set

Note how the `loadBalancerIP` still works as before when it's defined, for full backward compatibility.

```bash
$ helm template nextcloud . --set service.type=LoadBalancer --set service.loadBalancerIP=1.2.3.4 | grep Service -A 15
kind: Service
metadata:
  name: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    helm.sh/chart: nextcloud-3.6.0
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: app
spec:
  type: LoadBalancer
  loadBalancerIP: 1.2.3.4
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
```

## After - Forcing Previous Behavior

And if you still wish to template out the field with `nil` in the value as before, that is still supported by explicitly setting to `nil`.

```bash
$ helm template nextcloud . --set service.type=LoadBalancer --set service.loadBalancerIP=nil | grep Service -A 15
kind: Service
metadata:
  name: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    helm.sh/chart: nextcloud-3.5.22
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: app
spec:
  type: LoadBalancer
  loadBalancerIP: nil
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
```

## Before

Note the `nil` in the `loadBalancerIP` field.

```bash
$ helm template nextcloud . --set service.type=LoadBalancer | grep Service -A 15
kind: Service
metadata:
  name: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    helm.sh/chart: nextcloud-3.6.0
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: app
spec:
  type: LoadBalancer
  loadBalancerIP: nil
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
```

## Checklist 

- [ ] DCO has been [signed off on the commit](https://docs.github.com/en/github/authenticating-to-github/signing-commits).
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] (optional) Variables are documented in the README.md

2023-08-18 02:28 UTC, provokateurin approved these changes

2023-08-19 03:51 UTC, benyanke commented
Thanks for the approval @provokateurin  - is there anything else you need from me to get this merged?

2023-08-19 05:13 UTC, provokateurin commented
No, I'm just not experienced with the loadbalancer configuration so I want another review from @jessebot

2023-08-22 17:00 UTC, benyanke commented on charts/nextcloud/Chart.yaml
> +version: 4.0.1
understood, will do

2023-08-23 04:34 UTC, benyanke commented on charts/nextcloud/Chart.yaml
> +version: 4.0.1
Done

2023-08-23 04:36 UTC, benyanke commented
Hi @jessebot  - I've made the requested changes above.

2023-08-23 06:59 UTC, provokateurin requested changes

2023-08-23 06:59 UTC, provokateurin commented on charts/nextcloud/README.md
> +| `service.loadBalancerIP`                                   | LoadBalancerIp for service type LoadBalancer                     | `""`                         |
The formatting is a bit broken

2023-08-23 07:03 UTC, provokateurin commented
Can we please squash this mess? :see_no_evil:

2023-08-23 07:03 UTC, provokateurin approved these changes

2023-08-23 07:05 UTC, merged

2023-08-23 11:47 UTC, benyanke commented
Absolutely agree, squash merging is the way to go.