feat: keep PVCs when uninstalling helm chart
nextcloud/helm pull request #555
Opened 2024-04-10 19:00 UTC by Leptopoda

# Pull Request

## Description of the change

Keep nextcloud PVCs when uninstalling the helm chart

## Benefits

Most helm charts keep PVCs on uninstall. The current nextcloud approach is unexpected and thus may lead to data loss.
Learned that the hard way :sweat_smile: 

## Possible drawbacks

None that I'm aware of.

## Applicable issues

- fixes #53

## Additional information

## Checklist 

- [x] DCO has been [signed off on the commit](https://docs.github.com/en/github/authenticating-to-github/signing-commits).
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] (optional) Variables are documented in the README.md

2024-04-11 04:29 UTC, provokateurin commented
Duplicate of https://github.com/nextcloud/helm/pull/473

2024-04-11 04:31 UTC, provokateurin commented
Ok let's go with this PR because the other PR is stale...

2024-04-11 04:31 UTC, provokateurin requested changes

2024-04-11 04:31 UTC, provokateurin commented on charts/nextcloud/templates/nextcloud-data-pvc.yaml
> +    helm.sh/resource-policy: keep
This annotation should always be enabled, so it has to be outside of the `with`

2024-04-11 04:31 UTC, provokateurin commented on charts/nextcloud/templates/nextcloud-pvc.yaml
> +    helm.sh/resource-policy: keep
Same here

2024-04-11 08:08 UTC, provokateurin requested changes
The indentation should match the resulting indentation

2024-04-11 08:08 UTC, provokateurin commented on charts/nextcloud/templates/nextcloud-data-pvc.yaml
> +    {{- end }}
```suggestion
  {{- with .Values.persistence.nextcloudData.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
```

2024-04-11 08:08 UTC, provokateurin commented on charts/nextcloud/templates/nextcloud-pvc.yaml
> +    {{- end }}
```suggestion
  {{- with .Values.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
```

2024-04-11 08:13 UTC, provokateurin approved these changes

2024-04-11 08:14 UTC, merged

2026-06-28 17:49 UTC, filipcoja3108 commented
Why is it harcoded? Wouldnt it be better to make it configurable while keep being the default value? We have a use case where we want to delete the PVCs when a helm chart is uninstalled

2026-06-30 10:02 UTC, wrenix commented
Make a new PR to change it