Fix metrics secretKeyRef
nextcloud/helm pull request #86
Opened 2021-02-20 06:36 UTC by timtorChen

Currently, the metrics refer only to default secret name. This cause the metric pod cannot find the secret reference, if you use the different chart value of `.nextcloud.existingSecret.secretName`.

## Checklist 

- [x] DCO has been [signed off on the commit](https://docs.github.com/en/github/authenticating-to-github/signing-commits).
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).

2021-03-01 16:09 UTC, tvories requested changes

2021-03-01 16:09 UTC, tvories commented on charts/nextcloud/Chart.yaml
> +version: 2.5.7
Can you bump this to 2.5.12?

2021-03-02 08:35 UTC, timtorChen commented on charts/nextcloud/Chart.yaml
> +version: 2.5.7
done

2021-03-02 15:03 UTC, tvories approved these changes

2021-03-02 15:04 UTC, merged